# Generated by Django 5.2.6 on 2025-09-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=120)),
                ('department', models.CharField(choices=[('Medicare', 'Medicare'), ('Final Expense', 'Final Expense'), ('HVAC', 'HVAC'), ("CSR's", "CSR's"), ('management', 'Management')], max_length=32)),
                ('complaint_against', models.CharField(max_length=120)),
                ('complaint_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=120)),
                ('department', models.CharField(choices=[('Medicare', 'Medicare'), ('Final Expense', 'Final Expense'), ('HVAC', 'HVAC'), ("CSR's", "CSR's"), ('management', 'Management')], max_length=32)),
                ('date', models.DateField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=120)),
                ('department', models.CharField(choices=[('Medicare', 'Medicare'), ('Final Expense', 'Final Expense'), ('HVAC', 'HVAC'), ("CSR's", "CSR's"), ('management', 'Management')], max_length=32)),
                ('date', models.DateField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
