# Generated by Django 5.2.6 on 2025-09-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('category', models.CharField(choices=[('leave', 'Leave Requests'), ('complaint', 'Complaints'), ('resignation', 'Resignations'), ('all', 'All Types')], default='all', max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
