# Generated by Django 5.2.6 on 2025-09-11 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_notificationrecipient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationRecipient',
        ),
    ]
