# Generated by Django 5.2.6 on 2025-09-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_delete_notificationrecipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='department',
            field=models.CharField(choices=[('Medicare', 'Medicare'), ('Final Expense', 'Final Expense'), ('HVAC', 'HVAC'), ("CSR's", "CSR's"), ('Management', 'Management')], max_length=32),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='department',
            field=models.CharField(choices=[('Medicare', 'Medicare'), ('Final Expense', 'Final Expense'), ('HVAC', 'HVAC'), ("CSR's", "CSR's"), ('Management', 'Management')], max_length=32),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='department',
            field=models.CharField(choices=[('Medicare', 'Medicare'), ('Final Expense', 'Final Expense'), ('HVAC', 'HVAC'), ("CSR's", "CSR's"), ('Management', 'Management')], max_length=32),
        ),
    ]
