# Generated by Django 5.2.6 on 2025-09-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_complaint_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resignation',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
